### ISSUE TITLE
修改背景颜色透明度的时候 设置页面也会被应用透明

### ISSUE THREAD

**Issue by frg2089** [MUKAPP/BetterQQNT-MSpring-Theme#40]
我将MSpring主题与[背景插件](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin)搭配使用时注意到，
在我修改MSpring主题的背景透明度时，QQ的设置页面也会被影响。

这会造成一个后果，就是当QQ处在夜间模式时，
由于消除了黑色的背景，设置页面变成了白底白字。

文件管理器页面也会受影响。

<details>
<summary>夜间模式且背景全透明的设置页面的截图</summary>

![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/42184238/4c519133-3a86-473e-8fe8-47464283405e)

</details>

我目前的替代性解决方案是使用[Transitio](https://github.com/PRO-2684/transitio)加载一个内容是
```css
.setting-layout,
.nav-bar-container,
.file-manager-main {
  background-color: var(--background-04) !important;
}
```
的CSS。它似乎工作良好。
